import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Clapperboard, Film, Gauge } from "lucide-react";

function MixMetric({ label, published, target, ready, icon: Icon }: { label: string; published: number; target: number; ready: number; icon: React.ElementType }) {
  const remaining = Math.max(0, target - published);
  return <div className="rounded-xl border border-white/8 bg-black/20 p-4"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-red-400" /><Badge variant="outline" className="border-white/10 text-zinc-400">{published} / {target}</Badge></div><p className="mt-4 text-sm font-semibold text-zinc-100">{label}</p><p className="mt-1 text-xs leading-6 text-zinc-500">{remaining ? `المتبقي من الهدف: ${remaining}` : "اكتمل هدف اليوم"} · جاهز للمراجعة: {ready}</p></div>;
}

export default function ContentMixPanel() {
  const { data: mix } = trpc.daousha.contentMixStatus.useQuery();
  const { data: projectVideoAssets } = trpc.daousha.projectVideoAssets.useQuery();
  return <Card className="border-red-500/18 bg-[linear-gradient(145deg,rgba(69,10,10,.24),rgba(9,9,11,.86))]"><CardHeader className="flex-row items-start justify-between space-y-0"><div><CardTitle className="flex items-center gap-2 text-white"><Gauge className="h-5 w-5 text-red-400" /> توازن المحتوى اليومي</CardTitle><CardDescription className="mt-2 leading-6 text-zinc-500">تُقاس الأهداف من الفيديوهات المنشورة فعليًا فقط. لا يعني الهدف أن النظام سيخفض الجودة أو يتجاوز بوابات المراجعة.</CardDescription></div><Badge className="border border-red-500/20 bg-red-500/10 text-red-100 hover:bg-red-500/10">قصير أولًا · طويل بقيمة</Badge></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><MixMetric label="Reels / Shorts أصلية" published={mix?.publishedShorts ?? 0} target={mix?.dailyShortTarget ?? 4} ready={mix?.readyShorts ?? 0} icon={Clapperboard} /><MixMetric label="فيديوهات طويلة" published={mix?.publishedLongs ?? 0} target={mix?.dailyLongTarget ?? 2} ready={mix?.readyLongs ?? 0} icon={Film} /></div><div className="overflow-hidden rounded-xl border border-white/8"><div className="grid grid-cols-[1.4fr_.55fr_.7fr_.7fr] gap-2 border-b border-white/8 bg-black/25 px-3 py-2 text-[10px] text-zinc-500"><span>المشروع والنسخة</span><span>النوع</span><span>الحقوق/السلامة</span><span>المعاينة</span></div>{projectVideoAssets?.length ? projectVideoAssets.map(item => <div key={`${item.project.id}:${item.asset.id}`} className="grid grid-cols-[1.4fr_.55fr_.7fr_.7fr] gap-2 border-b border-white/6 px-3 py-2.5 text-xs last:border-b-0"><div><p className="font-medium text-zinc-200">{item.project.title}</p><p className="mt-1 truncate text-[10px] text-zinc-600">{item.asset.title}</p></div><Badge variant="outline" className="h-fit w-fit border-white/10 text-[10px] text-zinc-400">{item.project.contentFormat === "short" ? "Short / Reel" : "طويل"}</Badge><div className="space-y-1"><p className={item.asset.licenseStatus === "approved" ? "text-emerald-300" : "text-amber-200"}>حقوق: {item.asset.licenseStatus}</p><p className={item.asset.safetyStatus === "clear" ? "text-emerald-300" : "text-amber-200"}>سلامة: {item.asset.safetyStatus}</p></div><Badge variant="outline" className={item.project.previewAcknowledgedAt ? "h-fit w-fit border-emerald-500/25 text-emerald-200" : "h-fit w-fit border-amber-500/25 text-amber-200"}>{item.project.previewAcknowledgedAt ? "مُقَرّة" : "مطلوبة"}</Badge></div>) : <div className="p-4 text-sm text-zinc-500">لا توجد علاقات مشروع-فيديو مسجلة بعد.</div>}</div></CardContent></Card>;
}
