import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Activity, CalendarClock, CheckCircle2, CircleAlert, FolderKanban, RadioTower } from "lucide-react";

function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Activity }) { return <div className="rounded-xl border border-white/8 bg-black/20 p-4"><Icon className="h-4 w-4 text-red-400" /><p className="mt-3 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-zinc-500">{label}</p></div>; }

export default function NOVAOperationsCenter() {
  const dashboard = trpc.daousha.dashboard.useQuery();
  const workspace = trpc.nova.workspace.useQuery();
  const data = dashboard.data; const audit = workspace.data?.audit ?? [];
  return <section className="space-y-5" dir="rtl"><div><p className="text-xs font-medium tracking-[0.22em] text-red-300/70">NOVA / LIVE OPERATIONS</p><h2 className="mt-1 text-xl font-semibold text-white">مركز تشغيل المحتوى</h2><p className="mt-1 text-sm text-zinc-500">مؤشرات حية من مشروعات XDAW والجدولة وسجل المساعد، وليست محاكاة موارد نظام.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="مشروعات نشطة" value={data?.stats.activeProjects ?? 0} icon={FolderKanban} /><Metric label="مراجعات معلقة" value={data?.stats.reviewProjects ?? 0} icon={CircleAlert} /><Metric label="جدولات نشطة" value={data?.stats.activeSchedules ?? 0} icon={CalendarClock} /><Metric label="عمليات مساعد حديثة" value={audit.length} icon={Activity} /></div><div className="grid gap-5 xl:grid-cols-2"><Card className="border-white/8 bg-zinc-950/65"><CardHeader><CardTitle className="flex items-center gap-2 text-sm text-white"><RadioTower className="h-4 w-4 text-red-400" /> آخر عمليات النشر</CardTitle><CardDescription className="text-zinc-600">الحالة الموثقة من منفذ النشر فقط.</CardDescription></CardHeader><CardContent className="space-y-2">{(data?.runs ?? []).slice(0, 5).map(run => <div key={run.id} className="flex items-center justify-between rounded-lg border border-white/8 bg-white/[0.02] px-3 py-2 text-xs"><span className="text-zinc-300">{run.platform} · {run.visibility}</span><span className={["public_uploaded", "private_uploaded"].includes(run.status) ? "text-emerald-300" : run.status === "failed" || run.status === "blocked" ? "text-red-300" : "text-amber-300"}>{run.status}</span></div>)}{!data?.runs?.length && <p className="py-4 text-center text-xs text-zinc-600">لا توجد عمليات نشر حديثة في السجل.</p>}</CardContent></Card><Card className="border-white/8 bg-zinc-950/65"><CardHeader><CardTitle className="flex items-center gap-2 text-sm text-white"><CheckCircle2 className="h-4 w-4 text-red-400" /> آخر نشاط NOVA</CardTitle><CardDescription className="text-zinc-600">خطط وأدوات وقرارات مساعد قابلة للتدقيق.</CardDescription></CardHeader><CardContent className="space-y-2">{audit.slice(0, 5).map(event => <div key={event.id} className="rounded-lg border border-white/8 bg-white/[0.02] px-3 py-2 text-xs"><p className="text-zinc-300">{event.action}</p><p className="mt-1 text-zinc-600">{event.detail ?? event.decision}</p></div>)}{!audit.length && <p className="py-4 text-center text-xs text-zinc-600">لا توجد عمليات مساعد مسجلة بعد.</p>}</CardContent></Card></div></section>;
}
