import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Check, FileVideo, Loader2, ShieldAlert, X } from "lucide-react";
import { toast } from "sonner";

export default function ReviewQueue() {
  const utils = trpc.useUtils();
  const { data: assets } = trpc.daousha.assets.useQuery();
  const { data: projects } = trpc.daousha.projects.useQuery();
  const refresh = () => { utils.daousha.assets.invalidate(); utils.daousha.projects.invalidate(); utils.daousha.dashboard.invalidate(); };
  const assetReview = trpc.daousha.reviewAsset.useMutation({ onSuccess: () => { refresh(); toast.success("تم تحديث قرار المراجعة للمادة."); }, onError: error => toast.error(error.message) });
  const projectReview = trpc.daousha.transitionProject.useMutation({ onSuccess: () => { refresh(); toast.success("تم تحديث حالة المشروع."); }, onError: error => toast.error(error.message) });
  const pendingAssets = assets?.filter(asset => asset.licenseStatus === "pending" || asset.safetyStatus === "review") ?? [];
  const reviewProjects = projects?.filter(project => project.status === "review") ?? [];

  return <section className="grid gap-5 xl:grid-cols-2">
    <Card className="border-white/8 bg-zinc-950/60"><CardHeader><CardTitle className="flex items-center gap-2 text-white"><ShieldAlert className="h-5 w-5 text-red-400" /> مواد تحتاج قرارًا</CardTitle><CardDescription className="mt-2 text-zinc-500">الاعتماد يعني أن صاحب القرار راجع حق الاستخدام وحالة السلامة.</CardDescription></CardHeader><CardContent className="space-y-3">{pendingAssets.length === 0 ? <p className="rounded-lg border border-white/8 bg-white/[0.02] p-4 text-sm text-zinc-600">لا توجد مواد معلقة الآن.</p> : pendingAssets.map(asset => <div key={asset.id} className="rounded-xl border border-white/8 bg-white/[0.02] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-zinc-200">{asset.title}</p><p className="mt-1 text-xs text-zinc-600">{asset.licenseType}{asset.attribution ? ` · ${asset.attribution}` : ""}</p></div><Badge variant="outline" className="border-amber-500/25 text-amber-200">معلق</Badge></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" disabled={assetReview.isPending} onClick={() => assetReview.mutate({ assetId: asset.id, licenseStatus: "approved", safetyStatus: "clear" })} className="bg-red-600 hover:bg-red-500"><Check className="ml-1 h-3.5 w-3.5" /> اعتماد</Button><Button size="sm" disabled={assetReview.isPending} variant="outline" onClick={() => assetReview.mutate({ assetId: asset.id, licenseStatus: "held", safetyStatus: "review" })} className="border-white/10 text-zinc-300">تجميد للمراجعة</Button><Button size="sm" disabled={assetReview.isPending} variant="outline" onClick={() => assetReview.mutate({ assetId: asset.id, licenseStatus: "rejected", safetyStatus: "blocked" })} className="border-red-500/20 text-red-300"><X className="ml-1 h-3.5 w-3.5" /> رفض</Button></div></div>)}</CardContent></Card>
    <Card className="border-white/8 bg-zinc-950/60"><CardHeader><CardTitle className="flex items-center gap-2 text-white"><FileVideo className="h-5 w-5 text-red-400" /> مشروعات تنتظر إذنك</CardTitle><CardDescription className="mt-2 text-zinc-500">الاعتماد ينقل المشروع إلى جاهز للنشر، لكنه لا ينشره ولا يربط أي حساب.</CardDescription></CardHeader><CardContent className="space-y-3">{reviewProjects.length === 0 ? <p className="rounded-lg border border-white/8 bg-white/[0.02] p-4 text-sm text-zinc-600">لا توجد مشروعات في بوابة الموافقة الآن.</p> : reviewProjects.map(project => <div key={project.id} className="rounded-xl border border-white/8 bg-white/[0.02] p-4"><p className="text-sm font-semibold text-zinc-200">{project.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-zinc-600">{project.brief || "لا يوجد موجز للمشروع."}</p><div className="mt-4 flex gap-2"><Button size="sm" disabled={projectReview.isPending} onClick={() => projectReview.mutate({ projectId: project.id, status: "approved" })} className="bg-red-600 hover:bg-red-500">{projectReview.isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Check className="ml-1 h-3.5 w-3.5" />} اعتماد بشري</Button><Button size="sm" disabled={projectReview.isPending} variant="outline" onClick={() => projectReview.mutate({ projectId: project.id, status: "production" })} className="border-white/10 text-zinc-300">إرجاع للإنتاج</Button></div></div>)}</CardContent></Card>
  </section>;
}
